curl -X 'POST' '' -H 'Content-Type: application/json' \
  -d '
{
    "Flight": {
        "passengers": [
            {
                "name": "Don Jones",
                "delay": true,
                "quarantined": true,
                "military": false,
                "age": 35,
                "employee": false,
                "infant": false,
                "seat": 22,
                "status": "Diamond",
                "days since last IROP": 0,
                "milestone multiple": 0,
                "hours since last misconnect": 2.0,
                "is a 360 member": true,
                "last delta flight": "2023-01-28",
                "IROP severity level": 0,
                "days since SkyMiles member": 0,
                "days since new tier": 0,
                "medallion member": true,
                "corporate flyer": true,
                "unaccompanied minor": false,
                "skymiles member": true,
                "group booking size": 2,
                "last reveived recognition": "2021-02-17",
                "million miler": false,
                "missed connection": false,
                "qualifiedFlyer": null,
                "priority": null
                
            },
            {
                "name": "Ron Jones",
                "delay": true,
                "quarantined": false,
                "military": false,
                "age": 35,
                "employee": false,
                "infant": false,
                "seat": 22,
                "status": "Diamond",
                "days since last IROP": 0,
                "milestone multiple": 0,
                "hours since last misconnect": 2.0,
                "is a 360 member": true,
                "last delta flight": "2023-01-28",
                "IROP severity level": 0,
                "days since SkyMiles member": 0,
                "days since new tier": 0,
                "medallion member": true,
                "corporate flyer": true,
                "unaccompanied minor": false,
                "skymiles member": true,
                "group booking size": 2,
                "last reveived recognition": "2021-02-17",
                "million miler": false,
                "missed connection": false,
                "qualifiedFlyer": null,
                "priority": null
            },
            {
                "name": "Jane Doe",
                "delay": true,
                "quarantined": false,
                "military": false,
                "age": 35,
                "employee": false,
                "infant": false,
                "seat": 10,
                "status": "Gold",
                "days since last IROP": 15,
                "milestone multiple": 0,
                "hours since last misconnect": 19.0,
                "is a 360 member": true,
                "last delta flight": "2023-06-15",
                "IROP severity level": 0,
                "days since SkyMiles member": 0,
                "days since new tier": 1778,
                "medallion member": true,
                "corporate flyer": true,
                "unaccompanied minor": false,
                "skymiles member": true,
                "group booking size": 2,
                "last reveived recognition": "2022-09-05",
                "million miler": false,
                "missed connection": true,
                "qualifiedFlyer": null,
                "priority": null                
            },
            {
                "name": "Sally Edwards",
                "delay": false,
                "quarantined": false,
                "military": false,
                "age": 27,
                "employee": false,
                "infant": false,
                "seat": 46,
                "status": "Silver",
                "days since last IROP": 10,
                "milestone multiple": 2,
                "hours since last misconnect": 4.0,
                "is a 360 member": false,
                "last delta flight": "2021-03-19",
                "IROP severity level": 0,
                "days since SkyMiles member": 0,
                "days since new tier": 0,
                "medallion member": false,
                "corporate flyer": false,
                "unaccompanied minor": false,
                "skymiles member": true,
                "group booking size": 7,
                "last reveived recognition": "2022-09-05",
                "million miler": false,
                "missed connection": false,
                "qualifiedFlyer": null,
                "priority": null
            }
        ],
        "Flight Carrier": "DL",
        "flight time": "09:30",
        "flight date": "2023-09-05",
        "distance": 580
    }
}'
